stages:
  - build

variables:
  HARBOR_URL: "harbor.home.chingc.cc"   # 修改为您的Harbor地址
  HARBOR_PROJECT: "library"     # 修改为您的Harbor项目名称
  IMAGE_NAME: "maa-sync"           # 修改为您的镜像名称

build-and-push:
  stage: build
  image: quay.io/podman/stable  # 直接使用 Podman 客户端
  rules:
    - if: $CI_COMMIT_TAG             # 仅在推送tag时触发
      exists:                         # 且存在Dockerfile时执行
        - Dockerfile
  script:
    # 登录Harbor
    - podman login -u $HARBOR_USER -p $HARBOR_PASSWORD $HARBOR_URL

    # 构建镜像并打双标签
    - podman build -t $HARBOR_URL/$HARBOR_PROJECT/$IMAGE_NAME:$CI_COMMIT_TAG -t $HARBOR_URL/$HARBOR_PROJECT/$IMAGE_NAME:latest .

    # 推送带git tag的镜像
    - podman push $HARBOR_URL/$HARBOR_PROJECT/$IMAGE_NAME:$CI_COMMIT_TAG
    
    # 推送latest镜像
    - podman push $HARBOR_URL/$HARBOR_PROJECT/$IMAGE_NAME:latest
